name: fractal
description: A generic fractal generation module for creating and rendering various types of fractals.
version: 0.1.0-dev
homepage: http://t3infosecurity.com/
environment:
  sdk: ^3.4.0
dependencies:
  vector_math: ^2.1.0
  complex: ^0.7.2
dev_dependencies:
  image: ^3.0.1
  lints: ^3.0.0
  test: ^1.24.0