name: Dart Package CI

on:
  push:
    branches:
      - init-import
  pull_request:
    branches:
      - init-import

jobs:
  dart-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.5.4"

      - name: Install dependencies
        run: dart pub get

      - name: Verify Code
        run: dart format -o none --set-exit-if-changed lib

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: dart test
